apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: api-teste
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    insecure_skip_verify: "true"
spec:
  applicationPlans:
    api-teste-default:
      name: api-teste-default
  backendUsages:
    api-teste-echo-api:
      path: /api
  deployment:
    apicastHosted:
      authentication:
        oidc:
          authenticationFlow:
            directAccessGrantsEnabled: true
            implicitFlowEnabled: false
            serviceAccountsEnabled: true
            standardFlowEnabled: true
          credentials: headers
          issuerEndpointRef:
            name: api-teste-keycloak
          issuerType: keycloak
          jwtClaimWithClientID: azp
          jwtClaimWithClientIDType: plain
  mappingRules:
  - httpMethod: GET
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: POST
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: PUT
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: DELETE
    increment: 1
    metricMethodRef: hits
    pattern: /api
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  name: api-teste
  systemName: api-teste
  providerAccountRef: 
    name: tenant-apidev