apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: api-teste
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    insecure_skip_verify: "true"
spec:
  name: api-teste
  systemName: api-teste
  providerAccountRef: 
    name: tenant-apidev
  applicationPlans:
    api-teste-default:
      name: api-teste-default
  deployment:
    apicastHosted:
      authentication:
        oidc:
          authenticationFlow:
            directAccessGrantsEnabled: true
            implicitFlowEnabled: false
            serviceAccountsEnabled: true
            standardFlowEnabled: true
          credentials: headers
          issuerEndpointRef:
            name: api-teste-keycloak
          issuerType: keycloak
          jwtClaimWithClientID: azp
          jwtClaimWithClientIDType: plain
  backendUsages:
    api-teste-echo-api:
      path: /api
  mappingRules:
  - httpMethod: GET
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: POST
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: PUT
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: DELETE
    increment: 1
    metricMethodRef: hits
    pattern: /api
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  policies:
  - configuration:
      key:
        name: "{{ jwt.sub }}"
        name_type: liquid
        scope: service
      count: 10
      window: 60
    enabled: true
    name: edge
    version: builtin
  - configuration:
      request:
      - header: x-integrador-servico
        op: set
        value: '{{ original_request.path | remove_first: ''\/'' | split: ''\/'' | first }}'
        value_type: liquid
    enabled: true
    name: headers
    version: builtin
  - configuration: {}
    enabled: true
    name: apicast
    version: builtin
  - configuration:
      all_proxy: http://integrador-conecta-policy.3scale.svc.cluster.local:8081
      http_proxy: http://integrador-conecta-policy.3scale.svc.cluster.local:8081
      https_proxy: http://integrador-conecta-policy.3scale.svc.cluster.local:8081
    enabled: true
    name: camel
    version: builtin