apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: api-teste
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    insecure_skip_verify: "true"
spec:
  name: api-teste
  systemName: api-teste
  providerAccountRef: 
    name: tenant-apidev
  applicationPlans:
    api-teste-default:
      name: api-teste-default
  deployment:
    apicastHosted:
      authentication:
        oidc:
          authenticationFlow:
            directAccessGrantsEnabled: true
            implicitFlowEnabled: false
            serviceAccountsEnabled: true
            standardFlowEnabled: true
          credentials: headers
          issuerEndpointRef:
            name: api-teste-keycloak
          issuerType: keycloak
          jwtClaimWithClientID: azp
          jwtClaimWithClientIDType: plain
  backendUsages:
    api-teste-echo-api:
      path: /api
  mappingRules:
  - httpMethod: GET
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: POST
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: PUT
    increment: 1
    metricMethodRef: hits
    pattern: /api
  - httpMethod: DELETE
    increment: 1
    metricMethodRef: hits
    pattern: /api
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  policies:
  # Edge limiting - https://github.com/3scale/APIcast/blob/master/gateway/src/apicast/policy/rate_limit/
  - configuration:
      fixed_window_limiters:
        - key:
            name: "{{ jwt.sub }}"
            name_type: liquid
            scope: service
          count: 100 
          window: 60
    enabled: true
    name: rate_limit
    version: builtin
  # CORS - https://github.com/3scale/APIcast/tree/master/gateway/src/apicast/policy/cors
  - configuration:
      allow_origin: '*'
      max_age: 300
      allow_methods:
        - GET
        - HEAD
        - POST
        - PUT
        - DELETE
        - PATCH
        - OPTIONS
        - TRACE
        - CONNECT
    enabled: true
    name: cors
    version: builtin
  # RHSSO/Keycloak Role Check - https://github.com/3scale/APIcast/tree/master/gateway/src/apicast/policy/keycloak_role_check
  - configuration:
      scopes:
      - resource: '/api/admin'
        resource_type: plain
        realm_roles:
          - name: admin
            name_type: plain
      - resource: '/api/user'
        resource_type: plain
        methods:
          - GET
          - POST
        realm_roles:
          - name: user
            name_type: plain
    enabled: true
    name: keycloak_role_check
    version: builtin
  # APICast - default
  - configuration: {}
    enabled: true
    name: apicast
    version: builtin
  # Headers - https://github.com/3scale/APIcast/tree/master/gateway/src/apicast/policy/headers
  - configuration:
      request:
      - header: x-crls-user
        op: set
        value: '{{ jwt.preferred_username }}'
        value_type: liquid
      - header: x-crls-user-name
        op: set
        value: '{{ jwt.name }}'
        value_type: liquid
      - header: x-crls-user-email
        op: set
        value: '{{ jwt.email }}'
        value_type: liquid
    enabled: true
    name: headers
    version: builtin