apiVersion: capabilities.3scale.net/v1beta1
kind: Product
metadata:
  name: api
  namespace: 3scale
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    insecure_skip_verify: "true"
spec:
  applicationPlans:
    default:
      name: api-default
  backendUsages:
    api-echo-api:
      path: /api
  mappingRules:
  - httpMethod: GET
    increment: 1
    metricMethodRef: hits
    pattern: /
  - httpMethod: POST
    increment: 1
    metricMethodRef: hits
    pattern: /
  - httpMethod: PUT
    increment: 1
    metricMethodRef: hits
    pattern: /
  metrics:
    hits:
      description: Number of API hits
      friendlyName: Hits
      unit: hit
  name: api
  systemName: api